### ISSUE TITLE
problems in wheezy

### ISSUE THREAD

**Issue by clusterx** [virus2500/blocklist-with-ipset#1]
hello,
I'm using wheezy but the script hungs after:
Starting blocklist refresh
Creating Chain BLOCKLIST
Created ipset list blocklist
... nothing happens here

chains has been created but it wont import any rules:

Name: blocklist
Type: hash:ip
Header: family inet hashsize 4096 maxelem 65536 
Size in memory: 65656
References: 0
Members:

**Comment by virus2500** [comment]
i think everything is fixed by now :)
